name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request: # プルリクエスト作成・更新時にトリガー

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # PRにコメントを追加する権限
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v3
        with:
          # PR元の最新コミットを直接チェックアウトしてコミットメッセージを正しくします
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm # npmのキャッシュを有効化

      - name: Vercelデプロイ & PRコメント自動投稿
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: true # PRにプレビューURLを自動でコメントします
          vercel-version: latest
