name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main # mainブランチへのプッシュでトリガー

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v3

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm # npmのキャッシュを有効化

      - name: Vercel CLIのインストール
        run: npm install --global vercel@latest

      - name: Vercelの環境情報の取得
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: プロジェクトのビルド
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercelへの本番デプロイ
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
